version: '3.9'

services:
  localstack:
    image: localstack/localstack:2.0.1
    container_name: localstack
    environment:
      - SERVICES=sqs,sns,s3
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - PERSISTENCE=1
    # - DEBUG=1
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-/Users/avinashsaraf/work/apps_data/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
